[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200